include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - '**/*.config.dart'
    - '**/*.module.dart'
  errors:
    implementation_imports: error

linter:
  rules:
    unawaited_futures: true
    library_private_types_in_public_api: true
    always_declare_return_types: true
    prefer_final_locals: true
