name: quectochat
description: "A Flutter+Firebase chat"
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # стейт менеджмент
  flutter_bloc: 8.1.4
  bloc_concurrency: 0.2.4

  # автоматическое добавление зависимостей
  dep_gen: 1.1.5

  # хранение локальных данных
  path_provider: ^2.1.2

  # доступ к галерее
  photo_manager: 3.1.1

  # UI
  flutter_native_splash: ^2.4.0
  cupertino_icons: ^1.0.6
  string_to_color: ^2.0.0

  # кодогенерация
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1

  # иконка для приложения
  flutter_launcher_icons: ^0.13.1

  # firebase
  firebase_auth: ^5.1.0
  firebase_storage: ^12.0.1
  firebase_messaging: ^15.0.1
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # базовые линты
  flutter_lints: ^3.0.0

  # кодогенерация
  build_runner: 2.4.8
  freezed: 2.4.7

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: qicons
      fonts:
        - asset: assets/fonts/qicons.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy-bold.ttf
          weight: 700
        - asset: assets/fonts/gilroy-semibold.ttf
          weight: 600
        - asset: assets/fonts/gilroy-medium.ttf
          weight: 500

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFFFF"
  color_dark: "#2B333E"
  image: "assets/images/splash_logo.png"
  image_dark: "assets/images/splash_logo_dark.png"
  android_12:
    color: "#FFFFFF"
    color_dark: "#2B333E"
    image: "assets/images/splash_logo.png"
    image_dark: "assets/images/splash_logo_dark.png"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true