name: shared_ui
publish_to: none
description: Design system, themes, and reusable UI widgets.

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.38.0 <4.0.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.3.0
  shared_core:
    path: ../shared_core

  string_to_color: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - resources/icons/
    - resources/images/

  fonts:
    - family: Gilroy
      fonts:
        - asset: resources/fonts/gilroy-bold.ttf
          weight: 700
        - asset: resources/fonts/gilroy-semibold.ttf
          weight: 600
        - asset: resources/fonts/gilroy-medium.ttf
          weight: 500
